import { useState } from 'react'
import Landing from './pages/Landing.jsx'
import SecurityPulse from './pages/SecurityPulse.jsx'
import AdminCatalog from './pages/AdminCatalog.jsx'
import Orchestrator from './pages/Orchestrator.jsx'
import CommandCentre from './pages/CommandCentre.jsx'
import TeamsMock from './pages/TeamsMock.jsx'
import CipherLetter from './pages/CipherLetter.jsx'
import Amplifyverse from './pages/Amplifyverse.jsx'

const PAGES = [
  { id: 'landing', label: 'Overview' },
  { id: 'pulse', label: 'AI Pulse' },
  { id: 'catalog', label: 'Module Catalog' },
  { id: 'orchestrator', label: 'Scenario Orchestrator' },
  { id: 'command', label: 'Amplify Command Centre' },
  { id: 'teams', label: 'Teams Delivery' },
  { id: 'cipher', label: 'Prompt Lab' },
  { id: 'amplifyverse', label: 'The Amplifyverse' },
]

export default function App() {
  const [page, setPage] = useState('landing')
  // shared state: campaign generated by the orchestrator flows into command centre + teams
  const [campaign, setCampaign] = useState(null)

  const darkPages = ['landing', 'amplifyverse']

  return (
    <div className={`app ${darkPages.includes(page) ? 'app-dark' : 'app-light'}`}>
      <nav className="topnav">
        <div className="topnav-brand" onClick={() => setPage('landing')}>
          <span className="brand-mark">AMP</span>
          <span className="brand-name">Amplify</span>
        </div>
        <div className="topnav-links">
          {PAGES.map((p) => (
            <button
              key={p.id}
              className={`topnav-link ${page === p.id ? 'active' : ''}`}
              onClick={() => setPage(p.id)}
            >
              {p.label}
            </button>
          ))}
        </div>
        <div className="topnav-user">
          <span className="user-avatar">C</span>
          <span className="user-name">Caroline von Konigsmark</span>
          <span className="user-badge">ADMIN</span>
        </div>
      </nav>
      <main className="page">
        {page === 'landing' && <Landing onNavigate={setPage} />}
        {page === 'pulse' && <SecurityPulse />}
        {page === 'catalog' && <AdminCatalog onNavigate={setPage} />}
        {page === 'orchestrator' && (
          <Orchestrator onNavigate={setPage} campaign={campaign} setCampaign={setCampaign} />
        )}
        {page === 'command' && <CommandCentre onNavigate={setPage} campaign={campaign} />}
        {page === 'teams' && <TeamsMock onNavigate={setPage} campaign={campaign} />}
        {page === 'cipher' && <CipherLetter onNavigate={setPage} />}
        {page === 'amplifyverse' && <Amplifyverse onNavigate={setPage} />}
      </main>
    </div>
  )
}
